package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:57:31 Dubai.
*/
public class Hook211322 extends WPHook {

    public Hook211322() {
        super("2.11.322");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.eo";
    }

    @Override
    public String getUserMethod() {
        return "ac";
    }
}