package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:34 Dubai.
*/
public class Hook211248 extends WPHook {

    public Hook211248() {
        super("2.11.248");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.lqb";
    }

    @Override
    public String getUserMethod() {
        return "Qb";
    }
}