package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 10/07/2014 17:07:59 Dubai.
*/
public class Hook211284 extends WPHook {

    public Hook211284() {
        super("2.11.284");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.akj";
    }

    @Override
    public String getUserMethod() {
        return "n";
    }
}