package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 02/07/2014 18:21:44 Dubai.
*/
public class Hook211273 extends WPHook {

    public Hook211273() {
        super("2.11.273");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.j8";
    }

    @Override
    public String getUserMethod() {
        return "R";
    }
}