package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:21:52 Dubai.
*/
public class Hook211296 extends WPHook {

    public Hook211296() {
        super("2.11.296");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a3x";
    }

    @Override
    public String getUserMethod() {
        return "h";
    }
}