package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:24:56 Dubai.
*/
public class Hook211339 extends WPHook {

    public Hook211339() {
        super("2.11.339");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.aej";
    }

    @Override
    public String getUserMethod() {
        return "aX";
    }
}