package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:22:18 Dubai.
*/
public class Hook211357 extends WPHook {

    public Hook211357() {
        super("2.11.357");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.t4";
    }

    @Override
    public String getUserMethod() {
        return "w";
    }
}