
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:48:09 Dubai.
 */
public class Hook211177 extends WPHook {

    public Hook211177() {
        super("2.11.177");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.jj";
    }

    @Override
    public String getUserMethod() {
        return "Jb";
    }
}
