package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:30 Dubai.
*/
public class Hook211251 extends WPHook {

    public Hook211251() {
        super("2.11.251");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.xx";
    }

    @Override
    public String getUserMethod() {
        return "g";
    }
}