
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:28:57 Dubai.
 */
public class Hook211242 extends WPHook {

    public Hook211242() {
        super("2.11.242");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.bab";
    }

    @Override
    public String getUserMethod() {
        return "l";
    }
}
