package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:29:29 Dubai.
*/
public class Hook211373 extends WPHook {

    public Hook211373() {
        super("2.11.373");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.kb";
    }

    @Override
    public String getUserMethod() {
        return "aI";
    }
}