
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:46:55 Dubai.
 */
public class Hook211182 extends WPHook {

    public Hook211182() {
        super("2.11.182");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.v";
    }

    @Override
    public String getUserMethod() {
        return "S";
    }
}
