
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:36:16 Dubai.
 */
public class Hook211211 extends WPHook {

    public Hook211211() {
        super("2.11.211");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.rfb";
    }

    @Override
    public String getUserMethod() {
        return "O";
    }
}
