package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:25:21 Dubai.
*/
public class Hook211336 extends WPHook {

    public Hook211336() {
        super("2.11.336");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a53";
    }

    @Override
    public String getUserMethod() {
        return "l";
    }
}