
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:29:49 Dubai.
 */
public class Hook211240 extends WPHook {

    public Hook211240() {
        super("2.11.240");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ku";
    }

    @Override
    public String getUserMethod() {
        return "cc";
    }
}
