
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:36:40 Dubai.
 */
public class Hook211209 extends WPHook {

    public Hook211209() {
        super("2.11.209");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.job";
    }

    @Override
    public String getUserMethod() {
        return "wb";
    }
}
