
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:51:03 Dubai.
 */
public class Hook211169 extends WPHook {

    public Hook211169() {
        super("2.11.169");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.t4";
    }

    @Override
    public String getUserMethod() {
        return "D";
    }
}
