package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 09/07/2014 02:07:41 Dubai.
*/
public class Hook211283 extends WPHook {

    public Hook211283() {
        super("2.11.283");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.s7";
    }

    @Override
    public String getUserMethod() {
        return "I";
    }
}