package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 09/07/2014 02:06:48 Dubai.
*/
public class Hook211285 extends WPHook {

    public Hook211285() {
        super("2.11.285");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a3n";
    }

    @Override
    public String getUserMethod() {
        return "bd";
    }
}