
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:49:23 Dubai.
 */
public class Hook211173 extends WPHook {

    public Hook211173() {
        super("2.11.173");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.dkb";
    }

    @Override
    public String getUserMethod() {
        return "s";
    }
}
