package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 09/07/2014 02:08:30 Dubai.
*/
public class Hook211282 extends WPHook {

    public Hook211282() {
        super("2.11.282");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.l0";
    }

    @Override
    public String getUserMethod() {
        return "ao";
    }
}