
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:45:17 Dubai.
 */
public class Hook211188 extends WPHook {

    public Hook211188() {
        super("2.11.188");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.pg";
    }

    @Override
    public String getUserMethod() {
        return "hc";
    }
}
