package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:35 Dubai.
*/
public class Hook211247 extends WPHook {

    public Hook211247() {
        super("2.11.247");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.bob";
    }

    @Override
    public String getUserMethod() {
        return "Bb";
    }
}