package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:26 Dubai.
*/
public class Hook211258 extends WPHook {

    public Hook211258() {
        super("2.11.258");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.im";
    }

    @Override
    public String getUserMethod() {
        return "ab";
    }
}