
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:49:00 Dubai.
 */
public class Hook211174 extends WPHook {

    public Hook211174() {
        super("2.11.174");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.f1";
    }

    @Override
    public String getUserMethod() {
        return "f";
    }
}
