
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:30:40 Dubai.
 */
public class Hook211236 extends WPHook {

    public Hook211236() {
        super("2.11.236");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.fhb";
    }

    @Override
    public String getUserMethod() {
        return "U";
    }
}
