package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:23:38 Dubai.
*/
public class Hook211353 extends WPHook {

    public Hook211353() {
        super("2.11.353");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.fb";
    }

    @Override
    public String getUserMethod() {
        return "a6";
    }
}