package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:29 Dubai.
*/
public class Hook211254 extends WPHook {

    public Hook211254() {
        super("2.11.254");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.fj";
    }

    @Override
    public String getUserMethod() {
        return "aj";
    }
}