package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:24:29 Dubai.
*/
public class Hook211343 extends WPHook {

    public Hook211343() {
        super("2.11.343");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ud";
    }

    @Override
    public String getUserMethod() {
        return "q";
    }
}