package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:24 Dubai.
*/
public class Hook211263 extends WPHook {

    public Hook211263() {
        super("2.11.263");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ap0";
    }

    @Override
    public String getUserMethod() {
        return "av";
    }
}