package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:53:10 Dubai.
*/
public class Hook211331 extends WPHook {

    public Hook211331() {
        super("2.11.331");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.aw8";
    }

    @Override
    public String getUserMethod() {
        return "aW";
    }
}