package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 02/07/2014 18:23:03 Dubai.
*/
public class Hook211232 extends WPHook {

    public Hook211232() {
        super("2.11.232");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.cob";
    }

    @Override
    public String getUserMethod() {
        return "o";
    }
}