package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 07/07/2014 01:10:49 Dubai.
*/
public class Hook211277 extends WPHook {

    public Hook211277() {
        super("2.11.277");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.q5";
    }

    @Override
    public String getUserMethod() {
        return "a5";
    }
}