package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:24:04 Dubai.
*/
public class Hook211348 extends WPHook {

    public Hook211348() {
        super("2.11.348");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.vi";
    }

    @Override
    public String getUserMethod() {
        return "y";
    }
}