
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:37:57 Dubai.
 */
public class Hook211205 extends WPHook {

    public Hook211205() {
        super("2.11.205");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.g9";
    }

    @Override
    public String getUserMethod() {
        return "ub";
    }
}
