package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:49:25 Dubai.
*/
public class Hook211340 extends WPHook {

    public Hook211340() {
        super("2.11.340");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ja";
    }

    @Override
    public String getUserMethod() {
        return "J";
    }
}