package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 02/07/2014 18:21:17 Dubai.
*/
public class Hook211275 extends WPHook {

    public Hook211275() {
        super("2.11.275");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.m9";
    }

    @Override
    public String getUserMethod() {
        return "N";
    }
}