package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:21 Dubai.
*/
public class Hook211269 extends WPHook {

    public Hook211269() {
        super("2.11.269");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.cy";
    }

    @Override
    public String getUserMethod() {
        return "aq";
    }
}