
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:43:26 Dubai.
 */
public class Hook211192 extends WPHook {

    public Hook211192() {
        super("2.11.192");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.vu";
    }

    @Override
    public String getUserMethod() {
        return "Sb";
    }
}
