
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:53:10 Dubai.
 */
public class Hook211164 extends WPHook {

    public Hook211164() {
        super("2.11.164");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.kq";
    }

    @Override
    public String getUserMethod() {
        return "xb";
    }
}
