package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:21 Dubai.
*/
public class Hook211268 extends WPHook {

    public Hook211268() {
        super("2.11.268");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.hs";
    }

    @Override
    public String getUserMethod() {
        return "o";
    }
}