package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:39 Dubai.
*/
public class Hook211244 extends WPHook {

    public Hook211244() {
        super("2.11.244");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.o9";
    }

    @Override
    public String getUserMethod() {
        return "t";
    }
}