
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:34:07 Dubai.
 */
public class Hook211218 extends WPHook {

    public Hook211218() {
        super("2.11.218");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ey";
    }

    @Override
    public String getUserMethod() {
        return "r";
    }
}
