package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:59:41 Dubai.
*/
public class Hook211317 extends WPHook {

    public Hook211317() {
        super("2.11.317");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.vv";
    }

    @Override
    public String getUserMethod() {
        return "w";
    }
}