
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:38:21 Dubai.
 */
public class Hook211204 extends WPHook {

    public Hook211204() {
        super("2.11.204");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.u0";
    }

    @Override
    public String getUserMethod() {
        return "yb";
    }
}
