package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:27 Dubai.
*/
public class Hook211257 extends WPHook {

    public Hook211257() {
        super("2.11.257");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.vl";
    }

    @Override
    public String getUserMethod() {
        return "D";
    }
}