
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:51:26 Dubai.
 */
public class Hook211168 extends WPHook {

    public Hook211168() {
        super("2.11.168");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.xi";
    }

    @Override
    public String getUserMethod() {
        return "Yb";
    }
}
