package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:23:34 Dubai.
*/
public class Hook211294 extends WPHook {

    public Hook211294() {
        super("2.11.294");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.gj";
    }

    @Override
    public String getUserMethod() {
        return "a0";
    }
}