
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:40:41 Dubai.
 */
public class Hook211199 extends WPHook {

    public Hook211199() {
        super("2.11.199");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.xhb";
    }

    @Override
    public String getUserMethod() {
        return "S";
    }
}
