package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 07/07/2014 01:08:06 Dubai.
*/
public class Hook211280 extends WPHook {

    public Hook211280() {
        super("2.11.280");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.gd";
    }

    @Override
    public String getUserMethod() {
        return "Y";
    }
}