package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:28 Dubai.
*/
public class Hook211255 extends WPHook {

    public Hook211255() {
        super("2.11.255");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a5f";
    }

    @Override
    public String getUserMethod() {
        return "aL";
    }
}