
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:46:31 Dubai.
 */
public class Hook211184 extends WPHook {

    public Hook211184() {
        super("2.11.184");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ns";
    }

    @Override
    public String getUserMethod() {
        return "bb";
    }
}
