package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:22 Dubai.
*/
public class Hook211267 extends WPHook {

    public Hook211267() {
        super("2.11.267");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.gj";
    }

    @Override
    public String getUserMethod() {
        return "ai";
    }
}