
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:34:31 Dubai.
 */
public class Hook211217 extends WPHook {

    public Hook211217() {
        super("2.11.217");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.inb";
    }

    @Override
    public String getUserMethod() {
        return "f";
    }
}
