package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:58:42 Dubai.
*/
public class Hook211318 extends WPHook {

    public Hook211318() {
        super("2.11.318");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.er";
    }

    @Override
    public String getUserMethod() {
        return "r";
    }
}