
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:31:05 Dubai.
 */
public class Hook211234 extends WPHook {

    public Hook211234() {
        super("2.11.234");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.nx";
    }

    @Override
    public String getUserMethod() {
        return "cb";
    }
}
