package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:22 Dubai.
*/
public class Hook211266 extends WPHook {

    public Hook211266() {
        super("2.11.266");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.su";
    }

    @Override
    public String getUserMethod() {
        return "Z";
    }
}