package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:31:12 Dubai.
*/
public class Hook211371 extends WPHook {

    public Hook211371() {
        super("2.11.371");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.jm";
    }

    @Override
    public String getUserMethod() {
        return "F";
    }
}