
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:34:58 Dubai.
 */
public class Hook211215 extends WPHook {

    public Hook211215() {
        super("2.11.215");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.q4";
    }

    @Override
    public String getUserMethod() {
        return "j";
    }
}
