
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:37:33 Dubai.
 */
public class Hook211206 extends WPHook {

    public Hook211206() {
        super("2.11.206");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.fy";
    }

    @Override
    public String getUserMethod() {
        return "e";
    }
}
