
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:29:22 Dubai.
 */
public class Hook211241 extends WPHook {

    public Hook211241() {
        super("2.11.241");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.gsb";
    }

    @Override
    public String getUserMethod() {
        return "N";
    }
}
