package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:32 Dubai.
*/
public class Hook211249 extends WPHook {

    public Hook211249() {
        super("2.11.249");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.jr";
    }

    @Override
    public String getUserMethod() {
        return "Ub";
    }
}