
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:30:14 Dubai.
 */
public class Hook211238 extends WPHook {

    public Hook211238() {
        super("2.11.238");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.hc";
    }

    @Override
    public String getUserMethod() {
        return "nb";
    }
}
