package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:22:44 Dubai.
*/
public class Hook211355 extends WPHook {

    public Hook211355() {
        super("2.11.355");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.v4";
    }

    @Override
    public String getUserMethod() {
        return "aS";
    }
}