
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:31:30 Dubai.
 */
public class Hook211230 extends WPHook {

    public Hook211230() {
        super("2.11.230");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.fpb";
    }

    @Override
    public String getUserMethod() {
        return "l";
    }
}
