package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:27:11 Dubai.
*/
public class Hook211320 extends WPHook {

    public Hook211320() {
        super("2.11.320");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.oi";
    }

    @Override
    public String getUserMethod() {
        return "aB";
    }
}