package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:46:30 Dubai.
*/
public class Hook211347 extends WPHook {

    public Hook211347() {
        super("2.11.347");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.t8";
    }

    @Override
    public String getUserMethod() {
        return "v";
    }
}