
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:44:48 Dubai.
 */
public class Hook211189 extends WPHook {

    public Hook211189() {
        super("2.11.189");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.tj";
    }

    @Override
    public String getUserMethod() {
        return "nb";
    }
}
