package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 10/07/2014 17:07:20 Dubai.
*/
public class Hook211286 extends WPHook {

    public Hook211286() {
        super("2.11.286");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.bp";
    }

    @Override
    public String getUserMethod() {
        return "aB";
    }
}