package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:22:42 Dubai.
*/
public class Hook211295 extends WPHook {

    public Hook211295() {
        super("2.11.295");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.vg";
    }

    @Override
    public String getUserMethod() {
        return "aY";
    }
}