
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:33:43 Dubai.
 */
public class Hook211219 extends WPHook {

    public Hook211219() {
        super("2.11.219");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.sfb";
    }

    @Override
    public String getUserMethod() {
        return "jb";
    }
}
