package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:23 Dubai.
*/
public class Hook211265 extends WPHook {

    public Hook211265() {
        super("2.11.265");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a1h";
    }

    @Override
    public String getUserMethod() {
        return "a5";
    }
}