package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:24:26 Dubai.
*/
public class Hook211289 extends WPHook {

    public Hook211289() {
        super("2.11.289");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a54";
    }

    @Override
    public String getUserMethod() {
        return "ao";
    }
}