package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:26:16 Dubai.
*/
public class Hook211328 extends WPHook {

    public Hook211328() {
        super("2.11.328");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.jp";
    }

    @Override
    public String getUserMethod() {
        return "bf";
    }
}