
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:35:51 Dubai.
 */
public class Hook211212 extends WPHook {

    public Hook211212() {
        super("2.11.212");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.j2";
    }

    @Override
    public String getUserMethod() {
        return "o";
    }
}
