
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:38:45 Dubai.
 */
public class Hook211203 extends WPHook {

    public Hook211203() {
        super("2.11.203");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.rl";
    }

    @Override
    public String getUserMethod() {
        return "lb";
    }
}
