
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:32:51 Dubai.
 */
public class Hook211223 extends WPHook {

    public Hook211223() {
        super("2.11.223");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.klb";
    }

    @Override
    public String getUserMethod() {
        return "t";
    }
}
