package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:30:21 Dubai.
*/
public class Hook211372 extends WPHook {

    public Hook211372() {
        super("2.11.372");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.mb";
    }

    @Override
    public String getUserMethod() {
        return "a_";
    }
}