
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:41:06 Dubai.
 */
public class Hook211195 extends WPHook {

    public Hook211195() {
        super("2.11.195");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.d5";
    }

    @Override
    public String getUserMethod() {
        return "Rb";
    }
}
