package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:18:06 Dubai.
*/
public class Hook211311 extends WPHook {

    public Hook211311() {
        super("2.11.311");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.azz";
    }

    @Override
    public String getUserMethod() {
        return "aH";
    }
}