
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:47:46 Dubai.
 */
public class Hook211178 extends WPHook {

    public Hook211178() {
        super("2.11.178");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.pbb";
    }

    @Override
    public String getUserMethod() {
        return "cb";
    }
}
