package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:24 Dubai.
*/
public class Hook211261 extends WPHook {

    public Hook211261() {
        super("2.11.261");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.wr";
    }

    @Override
    public String getUserMethod() {
        return "aR";
    }
}