package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:32:14 Dubai.
*/
public class Hook211369 extends WPHook {

    public Hook211369() {
        super("2.11.369");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.uu";
    }

    @Override
    public String getUserMethod() {
        return "aH";
    }
}