package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:52:00 Dubai.
*/
public class Hook211333 extends WPHook {

    public Hook211333() {
        super("2.11.333");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.zw";
    }

    @Override
    public String getUserMethod() {
        return "ak";
    }
}