package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:48:16 Dubai.
*/
public class Hook211341 extends WPHook {

    public Hook211341() {
        super("2.11.341");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.avw";
    }

    @Override
    public String getUserMethod() {
        return "ad";
    }
}