
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:37:05 Dubai.
 */
public class Hook211207 extends WPHook {

    public Hook211207() {
        super("2.11.207");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.zz";
    }

    @Override
    public String getUserMethod() {
        return "W";
    }
}
