package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:26:44 Dubai.
*/
public class Hook211326 extends WPHook {

    public Hook211326() {
        super("2.11.326");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ajn";
    }

    @Override
    public String getUserMethod() {
        return "g";
    }
}