package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 01/07/2014 18:43:21 Dubai.
*/
public class Hook211272 extends WPHook {

    public Hook211272() {
        super("2.11.272");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.xt";
    }

    @Override
    public String getUserMethod() {
        return "P";
    }
}