
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:32:24 Dubai.
 */
public class Hook211224 extends WPHook {

    public Hook211224() {
        super("2.11.224");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.q9";
    }

    @Override
    public String getUserMethod() {
        return "ab";
    }
}
