package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:56:22 Dubai.
*/
public class Hook211323 extends WPHook {

    public Hook211323() {
        super("2.11.323");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.mm";
    }

    @Override
    public String getUserMethod() {
        return "Q";
    }
}