package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:55:03 Dubai.
*/
public class Hook211325 extends WPHook {

    public Hook211325() {
        super("2.11.325");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.h1";
    }

    @Override
    public String getUserMethod() {
        return "n";
    }
}