package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:25:48 Dubai.
*/
public class Hook211332 extends WPHook {

    public Hook211332() {
        super("2.11.332");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.w9";
    }

    @Override
    public String getUserMethod() {
        return "aY";
    }
}