package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:25 Dubai.
*/
public class Hook211260 extends WPHook {

    public Hook211260() {
        super("2.11.260");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.jj";
    }

    @Override
    public String getUserMethod() {
        return "aC";
    }
}