package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:45:07 Dubai.
*/
public class Hook211345 extends WPHook {

    public Hook211345() {
        super("2.11.345");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ee";
    }

    @Override
    public String getUserMethod() {
        return "aL";
    }
}