package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:18:35 Dubai.
*/
public class Hook211310 extends WPHook {

    public Hook211310() {
        super("2.11.310");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.d3";
    }

    @Override
    public String getUserMethod() {
        return "a4";
    }
}