
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:31:54 Dubai.
 */
public class Hook211226 extends WPHook {

    public Hook211226() {
        super("2.11.226");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.nz";
    }

    @Override
    public String getUserMethod() {
        return "s";
    }
}
