package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:20:07 Dubai.
*/
public class Hook211305 extends WPHook {

    public Hook211305() {
        super("2.11.305");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.jn";
    }

    @Override
    public String getUserMethod() {
        return "aJ";
    }
}