package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 02/07/2014 18:22:35 Dubai.
*/
public class Hook211259 extends WPHook {

    public Hook211259() {
        super("2.11.259");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.g4";
    }

    @Override
    public String getUserMethod() {
        return "o";
    }
}