package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:32:54 Dubai.
*/
public class Hook211365 extends WPHook {

    public Hook211365() {
        super("2.11.365");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.awn";
    }

    @Override
    public String getUserMethod() {
        return "bb";
    }
}