package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 29/08/2014 10:27:38 Dubai.
*/
public class Hook211319 extends WPHook {

    public Hook211319() {
        super("2.11.319");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp._m";
    }

    @Override
    public String getUserMethod() {
        return "bg";
    }
}