package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:20:53 Dubai.
*/
public class Hook211304 extends WPHook {

    public Hook211304() {
        super("2.11.304");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.br";
    }

    @Override
    public String getUserMethod() {
        return "C";
    }
}