
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:35:26 Dubai.
 */
public class Hook211214 extends WPHook {

    public Hook211214() {
        super("2.11.214");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.fob";
    }

    @Override
    public String getUserMethod() {
        return "Rb";
    }
}
