package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:19:15 Dubai.
*/
public class Hook211308 extends WPHook {

    public Hook211308() {
        super("2.11.308");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.bp";
    }

    @Override
    public String getUserMethod() {
        return "V";
    }
}