
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:33:17 Dubai.
 */
public class Hook211221 extends WPHook {

    public Hook211221() {
        super("2.11.221");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.pjb";
    }

    @Override
    public String getUserMethod() {
        return "hc";
    }
}
