package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:23 Dubai.
*/
public class Hook211264 extends WPHook {

    public Hook211264() {
        super("2.11.264");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.vx";
    }

    @Override
    public String getUserMethod() {
        return "ak";
    }
}