
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:47:20 Dubai.
 */
public class Hook211181 extends WPHook {

    public Hook211181() {
        super("2.11.181");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.mj";
    }

    @Override
    public String getUserMethod() {
        return "T";
    }
}
