package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 10/07/2014 17:06:41 Dubai.
*/
public class Hook211288 extends WPHook {

    public Hook211288() {
        super("2.11.288");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.tm";
    }

    @Override
    public String getUserMethod() {
        return "d";
    }
}