package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 22:00:34 Dubai.
*/
public class Hook211313 extends WPHook {

    public Hook211313() {
        super("2.11.313");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ho";
    }

    @Override
    public String getUserMethod() {
        return "bg";
    }
}