
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:50:38 Dubai.
 */
public class Hook211170 extends WPHook {

    public Hook211170() {
        super("2.11.170");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ubb";
    }

    @Override
    public String getUserMethod() {
        return "i";
    }
}
