package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 07/07/2014 01:09:59 Dubai.
*/
public class Hook211278 extends WPHook {

    public Hook211278() {
        super("2.11.278");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a8r";
    }

    @Override
    public String getUserMethod() {
        return "X";
    }
}