
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:51:52 Dubai.
 */
public class Hook211167 extends WPHook {

    public Hook211167() {
        super("2.11.167");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.tbb";
    }

    @Override
    public String getUserMethod() {
        return "R";
    }
}
