package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:20 Dubai.
*/
public class Hook211270 extends WPHook {

    public Hook211270() {
        super("2.11.270");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a49";
    }

    @Override
    public String getUserMethod() {
        return "ah";
    }
}