package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:37 Dubai.
*/
public class Hook211246 extends WPHook {

    public Hook211246() {
        super("2.11.246");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.hb";
    }

    @Override
    public String getUserMethod() {
        return "tb";
    }
}