
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:50:15 Dubai.
 */
public class Hook211171 extends WPHook {

    public Hook211171() {
        super("2.11.171");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ph";
    }

    @Override
    public String getUserMethod() {
        return "n";
    }
}
