package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:29 Dubai.
*/
public class Hook211252 extends WPHook {

    public Hook211252() {
        super("2.11.252");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.r9";
    }

    @Override
    public String getUserMethod() {
        return "j";
    }
}