package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:34:14 Dubai.
*/
public class Hook211360 extends WPHook {

    public Hook211360() {
        super("2.11.360");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.rv";
    }

    @Override
    public String getUserMethod() {
        return "aA";
    }
}