
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:52:47 Dubai.
 */
public class Hook211165 extends WPHook {

    public Hook211165() {
        super("2.11.165");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.xjb";
    }

    @Override
    public String getUserMethod() {
        return "y";
    }
}
