
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:39:43 Dubai.
 */
public class Hook211201 extends WPHook {

    public Hook211201() {
        super("2.11.201");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.v9";
    }

    @Override
    public String getUserMethod() {
        return "T";
    }
}
