package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:50:37 Dubai.
*/
public class Hook211271 extends WPHook {

    public Hook211271() {
        super("2.11.271");
    }

    @Override
    public String getPwdMethod() {
        return "b";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.yr";
    }

    @Override
    public String getUserMethod() {
        return "bb";
    }
}