
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:42:59 Dubai.
 */
public class Hook211193 extends WPHook {

    public Hook211193() {
        super("2.11.193");
    }

    @Override
    public String getPwdMethod() {
        return "d";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.o3";
    }

    @Override
    public String getUserMethod() {
        return "qb";
    }
}
