
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:46:07 Dubai.
 */
public class Hook211186 extends WPHook {

    public Hook211186() {
        super("2.11.186");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.yo";
    }

    @Override
    public String getUserMethod() {
        return "w";
    }
}
