package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:31 Dubai.
*/
public class Hook211250 extends WPHook {

    public Hook211250() {
        super("2.11.250");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ac";
    }

    @Override
    public String getUserMethod() {
        return "w";
    }
}