
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:45:44 Dubai.
 */
public class Hook211187 extends WPHook {

    public Hook211187() {
        super("2.11.187");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.xfb";
    }

    @Override
    public String getUserMethod() {
        return "W";
    }
}
