package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/06/2014 16:05:38 Dubai.
*/
public class Hook211245 extends WPHook {

    public Hook211245() {
        super("2.11.245");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.of";
    }

    @Override
    public String getUserMethod() {
        return "Ub";
    }
}