package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 28/07/2014 19:23:59 Dubai.
*/
public class Hook211290 extends WPHook {

    public Hook211290() {
        super("2.11.290");
    }

    @Override
    public String getPwdMethod() {
        return "f";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ck";
    }

    @Override
    public String getUserMethod() {
        return "aB";
    }
}