package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 05/09/2014 22:33:43 Dubai.
*/
public class Hook211362 extends WPHook {

    public Hook211362() {
        super("2.11.362");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.a9w";
    }

    @Override
    public String getUserMethod() {
        return "k";
    }
}