package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:55:50 Dubai.
*/
public class Hook211324 extends WPHook {

    public Hook211324() {
        super("2.11.324");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.b1";
    }

    @Override
    public String getUserMethod() {
        return "r";
    }
}