package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:51:17 Dubai.
*/
public class Hook211335 extends WPHook {

    public Hook211335() {
        super("2.11.335");
    }

    @Override
    public String getPwdMethod() {
        return "e";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp._7";
    }

    @Override
    public String getUserMethod() {
        return "E";
    }
}