package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 07/07/2014 01:09:05 Dubai.
*/
public class Hook211279 extends WPHook {

    public Hook211279() {
        super("2.11.279");
    }

    @Override
    public String getPwdMethod() {
        return "g";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ay4";
    }

    @Override
    public String getUserMethod() {
        return "aQ";
    }
}