package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
* AutoGenerated on 24/08/2014 21:54:19 Dubai.
*/
public class Hook211327 extends WPHook {

    public Hook211327() {
        super("2.11.327");
    }

    @Override
    public String getPwdMethod() {
        return "a";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.aiz";
    }

    @Override
    public String getUserMethod() {
        return "ad";
    }
}