
package net.maxters.droid.xpsd.whatsapp.pwd.hooks;

import net.maxters.droid.xpsd.whatsapp.pwd.WPHook;

/**
 * AutoGenerated on 27/06/2014 11:48:34 Dubai.
 */
public class Hook211175 extends WPHook {

    public Hook211175() {
        super("2.11.175");
    }

    @Override
    public String getPwdMethod() {
        return "c";
    }

    @Override
    public String getPwdClass() {
        return "com.whatsapp.ot";
    }

    @Override
    public String getUserMethod() {
        return "i";
    }
}
